name: Code style and lint

on:
  pull_request:
    branches:
    - master

  workflow_dispatch:

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: run tidy
      run: |
        npm install
        npm run tidy-check
